### ISSUE TITLE
Usage in pipelines?

### ISSUE THREAD

**Issue by brucellino** [jenkinsci/github-issues-plugin#12]
Hello! 

Is this plugin usable in a Jenkinsfile? Where can I find docs on how to do that?
Thanks!

**Comment by Daniel15** [comment]
I'm not very familiar with pipelines, but someone did add a Jenkinsfile example to the wiki page: https://plugins.jenkins.io/github-issues. Is that useful at all?

Searching Github also returns two usages of this plugin in Jenkinsfiles: https://github.com/search?q=GitHubIssueNotifier+filename%3AJenkinsfile&type=Code. I don't know if these actually work, but it could be a good starting point?

**Comment by brucellino** [comment]
Hi @Daniel15  - this is actually just what I was looking for. Thanks very much.
