### ISSUE TITLE
Can you change Jabber to XMPP?

### ISSUE THREAD

**Issue by Neustradamus** [jenkinsci/github-issues-plugin#13]
Can you change Jabber to XMPP?
It is XMPP since 2004.
-> https://github.com/jenkinsci/jabber-plugin

**Comment by Daniel15** [comment]
I don't maintain that plugin; you'll need to ask the maintainer, or send a pull request.

**Comment by Neustradamus** [comment]
Why close this ticket, it is the official repository!

I can create a new too, but it is not good.

**Comment by Daniel15** [comment]
This is the repository of the GitHub issues plugin, not the Jabber plugin 😄

**Comment by Neustradamus** [comment]
Can you open issues for other projects?

**Comment by Daniel15** [comment]
I only have control over this project, none of the other ones. The Jabber plugin might be using JIRA (https://issues.jenkins-ci.org/) for bugs.
