### ISSUE TITLE
Jenkins-Git Hooks error: We couldn’t deliver this payload: Failure when receiving data from the peer

### ISSUE THREAD

**Issue by findzaatar** [jenkinsci/github-issues-plugin#14]
Related issues: https://github.com/jenkins-x/jx/issues/5633

When I initially setup the CI hook I was still using localhost:8080 and obviously that ultimately wasn't going to work. 

Since then I've gone through the steps below and then restarted the Jenkins server and have relogged in to the Jenkins UI dash but the error above is what I'm currently seeing from Github. 

<img width="663" alt="Screenshot 2020-01-14 12 27 08" src="https://user-images.githubusercontent.com/11345614/72380037-7061b780-36c9-11ea-954a-2b75863f499c.png">

```
$ sudo nano /usr/local/opt/jenkins-lts/homebrew.mxcl.jenkins-lts.plist
```
and changed 127.0.0.1 to 0.0.0.0 

FYI: I would've posted this issue in the main Jenkins repo but there's no public issue tracking.

**Comment by Daniel15** [comment]
192.168.0.32 is a private IP on your own network. GitHub needs a public IP to hit, so you'll need to actually enter your public IP there. Depending on how your network is configured, you'll need to configure port forwarding on your router (if it's a home internet connection). You can use something like ngrok for temporary testing.

This is the wrong place for Jenkins discussions/bugs, it's just for the GitHub issues plugin. You probably want either the mailing list (https://jenkins.io/mailing-lists/) or the Jenkins JIRA bug tracker (https://issues.jenkins-ci.org/).

**Comment by sbd** [comment]
Isn't ngrok well-known as being massively insecure?

**Comment by himanshush13** [comment]
Hello @sbd 
any update or changes, or any luck about the issue, coz we are still facing it.

**Comment by login2ashishverma** [comment]
I am also facing the same issue, If anyone have solution suggest me
