### ISSUE TITLE
jira plugin issue in jenkins

### ISSUE THREAD

**Issue by srinivasareddyasha** [jenkinsci/github-issues-plugin#15]
Hi am srinivasa am trying to integrate jira plugins in jenkins but am getting some errors because i configured jenkins behind reverse proxy and jira behind reverse proxy both are in different regions when am configuring jira plugin it is giving so many exceptions. my need is in jira issues the jenkins build information has to be update in comment section and also in jenkins i need jira issue url please suggest me best way to configure this

**Comment by Daniel15** [comment]
Sorry, this is the wrong place to ask. This GitHub repo is for the "GitHub Issues" plugin, not for issues relating to Jenkins or JIRA. I'm not sure where this should go - perhaps you need to email the Jenkins mailing list.
