### ISSUE TITLE
x509 ssl certificate jenkins not responding 

### ISSUE THREAD

**Issue by rushins** [jenkinsci/github-issues-plugin#16]
Hello Support,
i setup jenkins with windows server and try to setup SSL using third party provider certificate. 
i follow this steps for ssl certifcation configuraration https://stackoverflow.com/questions/5313703/how-can-i-set-up-jenkins-ci-to-use-https-on-windows

Having issues with x509 certificate for Jenkins SSL port. 

Here are my steps 
1) generate key
keytool -genkey -keyalg RSA -keystore Jenkins.jks -alias example.com -keysize 2048
2) certificate request
keytool -certreq -Keystore jenkins.jks -alias example.com -file jenkins.csr -keysize 2048
3) sent Jenkins.csr to my provider ad got the return  cert with PKCS#7 cert .
4) import
keytool -import -trustcacerts -file jenkins.p7b -keystore jenkins.jks -alias example.com

Getting error related P7b not supported while import, so i requested x509 and received the file . 

I have imported x509 and keystore created, however the jenkins is not responding to the https port but jenkins is up and running. 
 
Any thought or help.
BR,
Rushi.

**Comment by Daniel15** [comment]
This is the issues area for one particular Jenkins plugin (Github Issues Plugin), not for Jenkins itself. Please use the Jenkins mailing list or bug tracker.

**Comment by rushins** [comment]
can you provide the location jenkins mailing  list or bug tracker.

**Comment by Daniel15** [comment]
https://jenkins.io/mailing-lists/
https://wiki.jenkins.io/display/JENKINS/How+to+report+an+issue
