### ISSUE TITLE
Unable to create issue even after configuring the Git Tokens

### ISSUE THREAD

**Issue by phanikumar1210** [jenkinsci/github-issues-plugin#6]
I am getting the following error even after configuring and after successful test connection with token.
**WARNING: No GitHub config available for this job, GitHub Issue Notifier will not run! Error: GitHub property not configured**

I have configured GitHub server

**Comment by Daniel15** [comment]
Did you also configure the "GitHub project" field for the job?

![](http://ss.dan.cx/2017/04/Yarn_End_To_End_Config_%5BJenkins%5D_-_Google_Chrome_02-19.27.21.png)

**Comment by phanikumar1210** [comment]
Thanks, it worked for me.

**Comment by adamwong246** [comment]
for anyone else, check you github url's format. Note that it ends in slash, not `.git` or `.html`
